[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.12.0"
ordered-float = "4.2.0"
rand = { version = "0.8.5", features = ["small_rng"] }
poloto = "19.1.2"
unwrap-match = "0.1.0"
rouille = "3.6.2"

[profile.release]
debug = true
